yolo_model:

  config_file:
    name: mission.cfg
  weight_file:
    name: mission_17100.weights
  threshold:
    value: 0.65
  detection_classes:
    names:
      - Red
      - Green
      - Left
      - StraightLeft
      - Parking
      - School
      - No-School
      - Crosswalk
      - BusOnly
      - Working
      - Bicycle
      - Left-turn
      - Cross
      - Bump
