yolo_model:

  config_file:
    name: mission.cfg
  weight_file:
    name: mission_14400.weights
  threshold:
    value: 0.35
  detection_classes:
    names:
      - Red
      - Green
      - Left
      - StraightLeft
      - Parking
